### ISSUE TITLE
pca10056 gpio port1 (PBxx) not supported after nrfx HAL

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#171]
Current implementation assumes that port is assigned to each pin during generation of the Pin objects. 
Hence, P0.04 -> PA4, and P1.04 -> PB4. 

After nrfx HAL was introduced the upper pins (GPIO1) cannot be addressed with the current implementation due to the fact that the nrfx gpio pin setup uses 32 + PIN and will resolve this internally: 
https://github.com/NordicSemiconductor/nrfx/blob/master/hal/nrf_gpio.h#L444

From what i see there is many alternatives on how to solve this easily, but i need some input on what is a preferred way of addressing these pins. 
1. Keep pin and port as is, and do a encode before accessing the nrfx HAL by calculating the pin number the HAL wants (32 * Pin->port + Pin)
2. Remove port member from Pin object itself, and depend on the nrfx addressing scheme, such that Pin on GPIO1 is known as 32->45, hence rename the textual name of the Pin to P0  to P45 as there is no longer need for a A and B port.

Any other suggestions or comments?

**Comment by glennrub** [comment]
Proposed #172 as quick-fix as this will fix the issue temporarily.

**Comment by aykevl** [comment]
As we now use the nrfx HAL, I think the best way would be removing the PORT variable and only using nrfx pin numbers.

**Comment by glennrub** [comment]
Thanks, Ayke! What i needed to hear. I have pushed a second PR, #173 which is a proper fix. This patch reduces toltal flash consumption as port is removed from all pin objects, and that the name is now without A or B to indicate port.

**Comment by aykevl** [comment]
Great! I haven't read through the PR itself (only the description) but on the surface it sounds good.

**Comment by glennrub** [comment]
Resolved by PR #173
