### ISSUE TITLE
cleanup boards mpconfigboard.h

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#178]
Currently many of the defined settings are not used, or overlapping with already existing configs. 
Typical config from pca10040:

```
#define MICROPY_PY_MACHINE_UART     (1)
#define MICROPY_PY_MACHINE_HW_PWM   (1)
#define MICROPY_PY_MACHINE_HW_SPI   (1)
#define MICROPY_PY_MACHINE_TIMER    (1)
#define MICROPY_PY_MACHINE_RTCOUNTER (1)
#define MICROPY_PY_MACHINE_I2C      (1)
#define MICROPY_PY_MACHINE_ADC      (1)
#define MICROPY_PY_MACHINE_TEMP     (1)
#define MICROPY_PY_HW_RNG           (1)

#define MICROPY_HW_HAS_LED          (1)
#define MICROPY_HW_HAS_SWITCH       (0)
#define MICROPY_HW_HAS_FLASH        (0)
#define MICROPY_HW_HAS_SDCARD       (0)
#define MICROPY_HW_HAS_MMA7660      (0)
#define MICROPY_HW_HAS_LIS3DSH      (0)
#define MICROPY_HW_HAS_LCD          (0)
#define MICROPY_HW_ENABLE_RNG       (0)
#define MICROPY_HW_ENABLE_RTC       (0)
#define MICROPY_HW_ENABLE_TIMER     (0)
#define MICROPY_HW_ENABLE_SERVO     (0)
#define MICROPY_HW_ENABLE_DAC       (0)
#define MICROPY_HW_ENABLE_CAN       (0)
```

Could some of these be removed if unused?

**Comment by glennrub** [comment]
My proposal would be to keep the port specific ones, deleting all the _HW_ ones inherited from the initial porting.
Also, i would suggest to rename the MICROPY_PY_HW_RNG one to MICROPY_PY_RANDOM_HW_RNG, to indicate which module it is configuring.

As a different task i could image to move LED from pyb module to machine and get a proper MICROPY_PY_MACHINE_LED define.

For non module configs like internal flash, i guess it makes most sense to have something like a _HW_ config (MICROPY_HW_HAS_BUILTIN_FLASH), unless we indicate this a different way, like "MICROPY_PY_OS_INTERNAL_FS"?

Any thoughts?

**Comment by aykevl** [comment]
Sounds good!
I once tried to enable `MICROPY_HW_ENABLE_RNG` but it doesn't seem to work. Most other defines of that sort aren't referenced anywhere at all, so can certainly be removed.

**Comment by glennrub** [comment]
There is still some pending things to be done on this issue before i close it. I have not addressed the LED move yet. However, i have been thinking a bit on this and looked at other ports. From what i see only stm and teensy port is having this pyb.LED object. I wonder if it would be better to align it with the newer ports and remove it fully (esp32/esp8266), and just use pin.value() to set it instead? Or, if we want to keep it, move it to a module called "board" instead of "pyb"?

**Comment by glennrub** [comment]
Proposing PR #202 to move `pyb` to a `board` module. The LED's should be easily deactivated if needed by just configuring the board to have no leds; `MICROPY_HW_HAS_LED (0)`.

**Comment by glennrub** [comment]
PR #202 merged. Closing issue.
