### ISSUE TITLE
RFC: Rename nrf5 to nrf5x?

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#50]
Should nrf5 root folder be renamed to nrf5x before upstream PR?
Comments appreciated :-)

**Comment by tralamazza** [comment]
yup, unless you have some insider information that nordic will release a non nrf5x ble chip =P

**Comment by glennrub** [comment]
https://www.nordicsemi.com/node_206/node_305/Product-Related-News/Nordic-Semiconductor-unveils-product-roadmap-for-low-power-cellular-Internet-of-Things  refers to nRF91 series.

**Comment by glennrub** [comment]
Is the conclusion that we should go for a rename of the base folder then? nrf5 to nrf5x

**Comment by tralamazza** [comment]
We have decided to go for "nrf", to not be bound to nrf5x models only.
