### ISSUE TITLE
examples: Fail to enter raw repl

### ISSUE THREAD

**Issue by xmeow** [tralamazza/micropython#60]
When I try to execute some example like 
`python pyboard.py test.py --device COM5`
the script return fail to enter raw repl. I got a pca10040 and success compile and enter normal repl mode.
How you guys run the examples? Cause they seem so delicious~

**Comment by glennrub** [comment]
This is how I do it.. 
Either I freeze my modules/scripts by moving them into the freeze/ folder, or I use the REPL "paste mode" (CTRL-E). 

We should probably take a look on how to get the raw repl up again if it is useful. I remember removing it from main.c main loop long back.

**Comment by glennrub** [comment]
Hi @xmeow, 

I have added back the raw REPL mode in PR #62. 

Honestly, i do not know how this raw REPL is suppose to work. Would you be able to help me verify this? It looked like you had an idea on how to use it :)

**Comment by xmeow** [comment]
Thank you so much, the freeze way works fine for me. But the pyboard.py script or ampy still return could not enter raw repl. I'm not sure if it is caused by disabling the flow control. I will dig further into this. Anyway thank you so much for such grate work.
