### ISSUE TITLE
bluetooth: REPL on nrf51 gets stuck if characters are typed to fast

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#83]
GDB backtrace when provoking the error:

(gdb) bt
#0  0x0002d7fc in ble_drv_attr_s_notify ()
#1  0x0002da0c in mp_hal_stdout_tx_strn ()
#2  0x0002e2a2 in readline_process_char ()
#3  0x0002e2fe in readline ()
#4  0x0002e504 in pyexec_friendly_repl ()
#5  0x000338de in main ()

**Comment by glennrub** [comment]
Could this have been related to #127?

**Comment by aykevl** [comment]
I've been thinking the same thing. I've never had this issue myself, though.

**Comment by glennrub** [comment]
In order to clean up a bit i'm closing this issue in this repo as the continuation of the nrf-port development should happen in mainline micropython repository after the merge. If the issue is still applicable it could be raised towards mainline repo.
