### ISSUE TITLE
nrf: Align include guards

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#90]
Align include guards with upstream commit 299bc625864b9e624ed599c94a5f95870516139a name conventions.

**Comment by tralamazza** [comment]
Why not just use `#pragma once`?!

**Comment by glennrub** [comment]
Also suggested here: https://github.com/micropython/micropython/pull/3180
I guess for now, nrf port should just be aligned with the rest.

**Comment by glennrub** [comment]
In order to clean up a bit i'm closing this issue in this repo as the continuation of the nrf-port development should happen in mainline micropython repository after the merge. If the issue is still applicable it could be raised towards mainline repo.
