### ISSUE TITLE
nrf/boards/microbit: Backport radio module

### ISSUE THREAD

**Issue by glennrub** [tralamazza/micropython#97]
Should this work simultanious with BLE? If so, it has to have two backends, one direct radio access and one requsting time from SD.

Could driver be put under nrf/boards/microbit/extra_drivers or similar and have a new boards drivers hook to be compiled in?

Could also be a generic radio module to keep compability from all nrf5 micropython ports to communicate with microbit radio.

Reference to micro:bit source: https://github.com/bbcmicrobit/micropython/blob/master/source/microbit/modradio.cpp

**Comment by aykevl** [comment]
A description of how to implement ESB along BLE. If I understand correctly, ESB is very similar to the microbit radio, so this could be useful.
https://devzone.nordicsemi.com/blogs/733/running-micro-esb-concurrently-with-ble/

**Comment by glennrub** [comment]
In order to clean up a bit i'm closing this issue in this repo as the continuation of the nrf-port development should happen in mainline micropython repository after the merge. If the issue is still applicable it could be raised towards mainline repo.
